
wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [32, 32, 32, 32, 90]
    rows: [10, 10, 10, 4, 4, 90]
  refreshInterval: 1
  mods:
    docker:
      type: docker
      enabled: true
      labelColor: lightblue
      position:
        top: 0
        left: 3
        height: 3
        width: 2
      refreshInterval: 1s
    git:
      commitCount: 5
      commitFormat: "[forestgreen]%h [grey]%cd [white]%s [grey]%an[white]"
      dateFormat: "%H:%M %d %b %y"
      enabled: true
      position:
        top: 3
        left: 3
        height: 2
        width: 2
      refreshInterval: 8s
      repositories:
      - "/home/stas/projects/shiori"
    digitalclock:
      color: orange
      enabled: true
      font: bigfont
      hourFormat: 24
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      refreshInterval: 1s
      title: "big clock"
      type: "digitalclock"
    ipinfo:
      colors:
      name: "lightblue"
      value: "white"
      enabled: true
      position:
        top: 0
        left: 2
        height: 1
        width: 1
      refreshInterval: 150
    feedreader:
      enabled: true
      feeds:
      - http://feeds.bbci.co.uk/news/rss.xml
      feedLimit: 10
      position:
        top: 1
        left: 1
        width: 2
        height: 1
      refreshInterval: 14400
    power:
      enabled: true
      position:
        top: 2
        left: 2
        height: 1
        width: 1
      refreshInterval: 15
      title: "⚡️"
    resourceusage:
      cpuCombined: false
      enabled: true
      position:
        top: 2
        left: 1
        height: 2
        width: 1
      refreshInterval: 1s
      showCPU: true
      showMem: true
      showSwp: true
    todoist:
      apiKey: ""
      enabled: true
      position:
        top: 0
        left: 0
        height: 3
        width: 1
      projects:
        - 2299741353
      refreshInterval: 1h
    textfile:
      enabled: true
      filePath: "~/.config/wtf/config.yml"
      format: true
      position:
        top: 3
        left: 0
        height: 2
        width: 1
      refreshInterval: 30
      wrapText: false
    uptime:
      args: ["-p"]
      cmd: "uptime"
      enabled: true
      position:
        top: 3
        left: 2
        height: 1
        width: 1
      refreshInterval: 30
      type: cmdrunner
